version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install gym

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Run Gym Environment Tests
          command: |
            . venv/bin/activate
            pytest tests/

workflows:
  version: 2
  test:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies